SELECT F.FISH_COUNT, F.MAX_LENGTH, F.FISH_TYPE
FROM (
    SELECT FISH_TYPE,
        AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS AVG_LENGTH,
        COUNT(*) AS FISH_COUNT,
        MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) F
WHERE F.AVG_LENGTH >= 33
ORDER BY F.FISH_TYPE;
