SELECT FHJ.FLAVOR
FROM (
    SELECT FH.FLAVOR, FH.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR
    ) FH JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J ON FH.FLAVOR = J.FLAVOR
    ORDER BY TOTAL DESC
    FETCH FIRST 3 ROWS ONLY -- MySQL 에서는 LIMIT 3 사용
) FHJ;